doc/containers.rst, immer/detail/hamts/node.hpp, test/box/recursive.cpp
This makes sure that recursive types can be built by using `immer::box`. This is enough for now, so this PR addresses #24 and #36.
=> Recursive types

immer/heap/free_list_heap.hpp, immer/heap/thread_local_free_list_heap.hpp, immer/heap/unsafe_free_list_heap.hpp
Because of initialization order issues, before this change, it could
happen that a global container using a free_list as part of its memory
policy would be initialized before the state of the free list.  This
fixes the problem, thus addressing issue #37
=> This fixes the problems when using containers in global variables

immer/refcount/refcount_policy.hpp
IMMER_SMT_PAUSE won't be defined on ARM builds, so we need to fall back to
using std::this_thread::yield().
=> Only use IMMER_SMT_PAUSE when it is defined

immer/heap/debug_size_heap.hpp
As discussed in https://github.com/arximboldi/immer/issues/78
I chose to hardcode it to 8 because the alternative of `sizeof(void*) * 2` is not really connected to how `std::max_align_t` is defined.
=> Fix debug_size_heap::extra_size to always be 8 on MinGW 32bit builds

CMakeLists.txt
`CMAKE_INSTALL_INCLUDEDIR` and `CMAKE_INSTALL_LIBDIR` used in `CMakeLists.txt` are defined in `GNUInstallDirs.cmake`. Without including this module, this command will fail:
```bash
$ cmake --build . --target install
```
>  -- Install configuration: "Debug"
-- Up-to-date: /cmake/Immer/ImmerConfig.cmake
CMake Error at cmake_install.cmake:60 (file):
file INSTALL given no DESTINATION
=> Add missing include call

immer/config.hpp
The macro to check for "[[nodiscard]]" compiler support did not work with MSVC 19.16 and produced warnings:
https://godbolt.org/z/2-EjTj
"warning C4067: unexpected tokens following preprocessor directive - expected a newline"
This patch removes the warning and enables the attribute, if the Microsoft compiler is running in C++17 mode.
=> Fix warnings with msvc + [[nodiscard]] support

immer/detail/hamts/bits.hpp
__popcnt64 is only available when compiling for 64bit targets
=> MSVC: support 32bit builds

immer/detail/hamts/node.hpp, shell.nix, test/set/generic.ipp
RFC @mrpi!
This fixes issue #88. It just makes the test you gave me pass, but I have not checked with other data-structures. Did you face similar problems with other containers indeed?
=> Fix issues with unaligned data types on immer::set

immer/config.hpp, immer/detail/hamts/node.hpp, immer/detail/rbts/node.hpp, immer/detail/rbts/position.hpp, immer/detail/rbts/rbtree.hpp, immer/detail/rbts/rrbtree.hpp
It's unfortunate that the data layout of the library depends on the value of the NDEBUG macro, because it makes the code throw an assertion error if a library that includes immer is built with NDEBUG and then an application that includes immer but does not set NDEBUG links against that library. So I moved the functionality to set whether tagged nodes exist into config.hpp, and allowed it to be set by the user. We then create a new macro, assertKind, which we use instead of assert to guard the assertions that depend on tagged nodes.
=> Make tagged nodes configurable

extra/fuzzer/flex-vector.cpp
A missing header was found while testing immer fuzzers.
=> add missing include in flex-vector fuzzer

immer/detail/rbts/operations.hpp, immer/detail/rbts/rrbtree.hpp
As reported in #101, compiling with clang when using some versions of `libstdc++6`, such as 5.4, gives compilation errors. These can be fixed by replacing all list-initialised tuples with calls to `std::make_tuple`.
Fixes #101
=> Fix compatibility with clang when using some libstdc++6 versions

immer/array_transient.hpp, test/array_transient/default.cpp
Fixes #111.
I've checked that my changes to array_transient.hpp compile. I have not checked that my changes to test/array_transient/default.cpp compile.
as to "why doesn't the compiler complain that the default value is nonsensical, if you don't use the default value?" i have no answer. templates? sfinae?
=> Fix compilation error when default-initializing array_transient

immer/detail/rbts/position.hpp
This replaces all occurrences of `1 << shift_` with `size_t{1} << shift_`.
Fixes "[potential] issues in containers with more than 2^32 elements (on amd64 machines at least)." See #11.
=> Fix position.hpp integer shift warnings on 64-bit systems

CMakeLists.txt
When immer is used as part of a larger project hierarchy, the parent
will usually want/need to disable the non-essential parts of immer.
Some of the tests, examples, etc. will clash with things from other
projects, so being able to disable them in a project-specific way is
essential.
=> Minimal changes to support inclusion via add_subdirectory()

immer/detail/combine_standard_layout.hpp, immer/detail/iterator_facade.hpp
- Add defined(__GNUC__) guard to include to avoid "undefined symbol" warning
- iterator_facade doesn't need to derive from std::iterator; should explicitly define type categories instead
=> Minor fixes: MSVC static analysis warnings

.travis.yml, CMakeLists.txt, extra/fuzzer/CMakeLists.txt, extra/fuzzer/array-gc.cpp, extra/fuzzer/array.cpp, extra/fuzzer/flex-vector-gc.cpp, extra/fuzzer/flex-vector.cpp, extra/fuzzer/fuzzer_input.hpp, extra/fuzzer/map-gc.cpp, extra/fuzzer/map.cpp, extra/fuzzer/set-gc.cpp, extra/fuzzer/set.cpp, extra/fuzzer/vector-gc.cpp, extra/fuzzer/vector.cpp, shell.nix
In order to address #102, working towards ideal integration, we first do some build system changes to:
1. Make it easier to build the fuzzers from oss-fuzz, such that `make fuzzers` suffices and builds all fuzzers, automatically using the OSS Fuzz provided fuzzer engine if available
2. Make sure fuzzers are also built and minimally tested on our Travis CI
FYI @luismerino
=> Integrate OSS Fuzz

immer/detail/hamts/bits.hpp, immer/detail/hamts/champ.hpp, immer/detail/hamts/champ_iterator.hpp, immer/detail/hamts/node.hpp
Hi, a small pr from me as was discussed earlier.
I was fighting with integer promotion for some time and the only solution I found so far is to use casts for non-const expressions. Otherwise we get `popcount()` overload ambiguity...
Please take a look and probably you could suggest a better solution for that :)
=> Use smaller ints for bitmap_t if applicable

.clang-format, immer/config.hpp, immer/detail/arrays/no_capacity.hpp, immer/detail/arrays/node.hpp, immer/detail/arrays/with_capacity.hpp, immer/detail/hamts/champ.hpp, immer/detail/hamts/node.hpp, immer/detail/rbts/node.hpp, immer/detail/rbts/operations.hpp, immer/detail/rbts/rbtree.hpp, immer/detail/rbts/rrbtree.hpp, immer/detail/util.hpp, immer/heap/gc_heap.hpp, immer/heap/malloc_heap.hpp, immer/map.hpp, test/map/generic.ipp, test/vector/generic.ipp
Replaces all try/catch/throw keyword usage with a set of macros that are
appropriately defined in config.hpp based on the status of the
`cxx_exceptions` compiler feature.
Reported in issue #160.
=> Make excpetions optional depending on build-time feature checks.

immer/array.hpp, immer/array_transient.hpp, immer/box.hpp, immer/detail/arrays/no_capacity.hpp, immer/detail/arrays/node.hpp, immer/detail/arrays/with_capacity.hpp, immer/detail/combine_standard_layout.hpp, immer/detail/hamts/bits.hpp, immer/detail/hamts/node.hpp, immer/detail/rbts/bits.hpp, immer/detail/rbts/node.hpp, immer/detail/rbts/rbtree.hpp, immer/experimental/detail/dvektor_impl.hpp, immer/experimental/dvektor.hpp, immer/heap/cpp_heap.hpp, immer/heap/free_list_heap.hpp, immer/heap/split_heap.hpp, immer/heap/thread_local_free_list_heap.hpp, immer/heap/unsafe_free_list_heap.hpp, immer/map.hpp
The former needed for the new exception macros and the latter for the
usage of std::size_t.
Minor include ordering changes too.
=> Added missing <immer/config.hpp> and <cstddef> includes

immer/detail/arrays/no_capacity.hpp, immer/detail/arrays/with_capacity.hpp, immer/detail/rbts/rbtree.hpp, immer/detail/rbts/rrbtree.hpp, immer/map.hpp
Standard exceptions like `std::out_of_range` are defined in `<stdexcept>`, not in `<exception>`.
This fixes compilation issues i had with MSVC if I didn't include `<stdexcept>` before including some immer headers.
Thanks for this library btw !
=> Change <exception> includes to <stdexcept> when using standard exceptions

immer/detail/rbts/rrbtree.hpp, immer/map.hpp, immer/set.hpp, test/map/generic.ipp, test/set/generic.ipp
I opened this [issue](https://github.com/arximboldi/immer/issues/183) but then I though I could give it a try myself.
What I did was the following: whenever you refer to `K` as key type I replaced it with a template parameter. This allows you to put in any type that is supported by the hash object. I followed the c++20 convention for `std::unordered_map` such that those new functions only participate in overload resolution if `Hash::is_transparent` is a valid type.
This is just a proof of concept. There are more things one could consider:
- add template overloads to other member functions like `erase`.
- write more tests for other functions as well 🙈 
I added `immer/detail/rbts/rrbtree.hpp` because newer compilers no longer include `<limits>` as part of other stl headers.
=> Transparent Hash for Map and Sets

immer/algorithm.hpp, immer/detail/hamts/bits.hpp, immer/detail/hamts/champ.hpp, immer/detail/hamts/node.hpp, immer/map.hpp, immer/set.hpp, test/map/generic.ipp, test/set/generic.ipp
This is the implementation of a diff algorithm for immer::map. It compares two immer::map instances and calls respective lambda functions when keys were added or removed or when the value of a key changed. When data is shared among the two maps, the algorithm will not need to compare shared subtrees of the map.
We plan to use this for an undo feature.
The diff algorithm has following signature:
̂`map::diff(map const& other, AddedFn&& added, ChangedFn&& changed, RemovedFn&& Removed)`
where the lambdas have the signature:
```
void AddedFn(std::pair<Key, Value> const& added_entry)
void ChangedFn(std::pair<Key, Value> const& old_item, std::pair<Key, Value> const& new_data)
void RemovedFn(std::pair<Key, Value> const& removed_entry)
```
Usage:
```
immer::map<int, int> old_snapshot; // …
```
=> Add diffing algorithm to maps

.github/workflows/test.yml, .gitignore, Package.swift, spm.cpp
Adds a Swift Package so immer can be used easily in Xcode projects. SPM doesn't know about header-only libraries, so it required adding a source file (spm.cpp). We can move this file wherever you want.
=> Add Swift Package

benchmark/set/insert.hpp, benchmark/set/insert.ipp, extra/fuzzer/fuzzer_input.hpp, immer/map.hpp, immer/map_transient.hpp, immer/set.hpp, immer/set_transient.hpp, test/flex_vector/fuzzed-0.cpp, test/flex_vector/fuzzed-1.cpp, test/flex_vector/fuzzed-2.cpp, test/flex_vector/fuzzed-3.cpp, test/flex_vector/fuzzed-4.cpp, test/map/generic.ipp, test/map_transient/B3.cpp, test/map_transient/B6.cpp, test/map_transient/default.cpp, test/map_transient/gc.cpp, test/map_transient/generic.ipp, test/set/generic.ipp, test/set_transient/B3.cpp, test/set_transient/B6.cpp, test/set_transient/default.cpp, test/set_transient/gc.cpp, test/set_transient/generic.ipp
This PR is the first step towards the full implementation of transients for all [HAMT](https://en.wikipedia.org/wiki/Hash_array_mapped_trie)-based data-structures: `map` and `set`. 
In this PR we do define the interface in two modes:
- Using the special types `map_transient` and `set_transient`, which define a mutable interface (similar to the case of `vector_transient` and alike). This is required to benefit from the optimizations brought about by transients when using a tracing garbage collector.
- Using `std::move(x)...` when performing an operation on an immutable map. This will incur in the same performance benefit as the former when using reference counting for garbage collection (default) and is the recommended way to benefit from it.
In this PR we define and test the interface. We …
=> Sketch transients for HAMT-based data-structures

benchmark/set/insert.ipp, immer/detail/hamts/champ.hpp, immer/detail/hamts/node.hpp, immer/map.hpp, immer/map_transient.hpp, immer/set.hpp, immer/set_transient.hpp
This PR adds basic transience for insertion into HAMT based data-structures.
Affected methods are:
* **`immer::map`**
- `set() &&`
- `insert() &&`
* **`immer::set`**
- `insert() &&`
* **`immer::map_transient`** 
- `set()`
- `insert()`
* **`immer::set_transient`** 
- `insert()`
In this optimization, when a node is reusable during insertion, it is mutated in place instead of adding creating a new node. For now, we can do this only when the resulting node is the same size as it was. For small maps and sets (< 16 elements), this does not have much of an effect. But as the map grows and grows, we can see the effect of this optimization really taking over. This is particularly notable when the value type stored in the map is small, so copying inner nodes and touching reference counts dominates …
=> Implement transients for map and set

immer/config.hpp, immer/detail/arrays/node.hpp, immer/detail/arrays/with_capacity.hpp, immer/detail/hamts/champ.hpp, immer/detail/hamts/node.hpp, immer/detail/rbts/node.hpp, immer/detail/rbts/operations.hpp, immer/detail/rbts/rrbtree.hpp, immer/detail/util.hpp
In previous PR's we optimized "mutating" insertions by changing nodes in place when possible. However, whenever the change in-place was not possible because the new node needed is of a different size, the operation was performed exactly like in the immutable case.
This PR implements the realization that, when the node needs to be to be reallocated, we can still do things in a significantly faster way. In that case, we can "move" things out of the old node. When using reference counting, this means skipping touching the reference counts at all for inner nodes. For value buffers, we use std::move() potentially saving further allocations or reference count touches.
In some local testing, this brings the performance of mutating operations to 1.5X to 2.5X the performance of std::unordered_map, …
=> HAMT transients: move mutable inner nodes when posible during insertion

extra/fuzzer/map-gc.cpp, extra/fuzzer/map.cpp, immer/detail/hamts/champ.hpp, immer/map.hpp, immer/map_transient.hpp, immer/table.hpp, immer/table_transient.hpp, test/map/default.cpp, test/map/generic.ipp, test/map_transient/generic.ipp, test/table/generic.ipp, test/table_transient/generic.ipp
Among some extra fixes, this includes the changes discussed in our last meeting. This is:
- Introduce a new method `update_if_exists` that updates the value only when the key is present in the dictionary. Fixes #169 
- Improve the debugging API:
* A new `summary` type is added to the `champ_debug_stats` to obtain the summary as a value, so you can serialize it your own way.
* The default serialization is now done via a `operator<<`, so you can stream it to strings or other logging mecanism. This is a function of the `champ_debug_stats::summary` type.
* The `champ_debug_stats` now provide an `operator+`, so you can accumulate statistics from multiple maps into one. 
=> More Meta improvements

immer/algorithm.hpp, immer/detail/hamts/champ.hpp, immer/detail/hamts/node.hpp, immer/detail/rbts/operations.hpp, immer/detail/util.hpp, immer/map.hpp, immer/set.hpp, immer/table.hpp, test/algorithm.cpp, test/map/gc.cpp, test/map/generic.ipp, test/set/gc.cpp, test/set/generic.ipp
1. This solves an issue where:
```c++
auto v = immer::vector<int>{};
immer::for_each(v, [](int& x) {
x = 42;
})
```
Would work, mutating the contents of the vector!!! This problem did exist for various callback-based functions. This fixes it everywhere.
2. This also solves an issue where transient updates on HAMT's would be too eager, moving out values that they should really not move!
=> Fix: iteration over data-structures would inadvertibly allow mutation + HAMT's move out value bug

immer/detail/hamts/champ.hpp, immer/detail/hamts/node.hpp, immer/detail/rbts/node.hpp, immer/detail/rbts/operations.hpp, immer/refcount/no_refcount_policy.hpp, immer/refcount/refcount_policy.hpp, immer/refcount/unsafe_refcount_policy.hpp, test/memory/refcounts.cpp
The `dec_unsafe()` member of the refcount policies allows one to decrement the reference count without dealing with the resulting reference count. While there are some very rare situations where that is safe to do, in reality, this can lead to rare but subtle memory leaks when in a multi-threaded context.
Therefore, I have decided to remove this method completely. In most cases, we just replace it with a call to `dec()`.
In most scenarios this change should not affect performance. There are a couple of cases in the vector implementation where it may even improve it, as we touch reference counts less.
=> Remove all usage of `dec_unsafe` from the code-base

immer/detail/hamts/champ.hpp, test/map/generic.ipp
This fixes a couple of issues:
1. The dense value and child utilizations were swapped.
2. You could get inocuous `nan`s when there were no child or no values when computing the dense utilization.
=> Fix debug stats

immer/detail/hamts/champ.hpp
Clang throws a warning about this unknown gcc pragma. This is bad when we have warnings -> errors on.
=> make clang ignore gcc pragma warning for champ

benchmark/set/memory/basic-string-long.cpp, benchmark/set/memory/basic-string-short.cpp, benchmark/set/memory/basic-unsigned.cpp, benchmark/set/memory/exp-string-long.cpp, benchmark/set/memory/exp-string-short.cpp, benchmark/set/memory/exp-unsigned.cpp, benchmark/set/memory/lin-string-long.cpp, benchmark/set/memory/lin-string-short.cpp, benchmark/set/memory/lin-unsigned.cpp, benchmark/set/memory/memory.hpp, shell.nix
The exection of these is not automated yet.  We suggest running them with:
```bash
valgrind --tool=massif --detailed-freq=1 --max-snapshots=1000 <BENCHMARK>
```
The output file can then be studied with a tool like [massif-visualizer](https://github.com/KDE/massif-visualizer) (you may install it with `nix-shell -p massif-visualizer`).
These are some sample outputs:
**set-memory-lin-string-long**
This one shows the massive effects of structural sharing, when we are interested in taking multiple copies of a data-structure (snapshots). We produce a map of N 2^18 (~250K) strings and then we produce 128 updates, taking a "snapshot" on every step. 
We see that for `std::map` and `std::unordered_map` (the two first "peaks"), after the initial container is built, memory usage (and time!) grows in …
=> Add benchmarks for checking CHAMP memory usage

immer/detail/rbts/node.hpp, immer/detail/rbts/rrbtree.hpp, immer/flex_vector.hpp
This is a result of https://github.com/arximboldi/immer/issues/244.
This is just an idea how one could make the move constructor and assignment operator `noexcept`.
I used `aligned_storage` to statically reserve some memory for the nodes.
However, while I type this description I noticed a problem: I'm not familiar with the mechanism the frees memory. There is nothing that prevents the code from attempting to free the statically allocated buffers.
A possible solution would be to keep the ref count always above 0.
=> `flex_vector` nothrow move constructible/assignable

CMakeLists.txt
There is an vcpkg issue: https://github.com/microsoft/vcpkg/issues/28864, some users need use `find_package(immer VERSION 0.8.0)` feature. 
But this port doesn't have this feature. So I submit this PR to add export CMake Config version file, this will fix the use of find special version of `immer` like `find_package(immer VERSION 0.8.0)`, the parameter `SameMajorVersion` applies to the version with major 0.
=> Add export CMake Config version file

tools/gdb_pretty_printers/autoload.py
A while after making the initial commit in #255, it came to my attention that `__file__` isn't actually a terribly reliable way to find the source filename. This change should make the loading process more robust, and work in more contexts.
=> Make pretty-printer loading more robust

immer/detail/hamts/node.hpp
The following code from your documentation:
```c++
using map_t = immer::map<std::string, int>;
struct part{};
struct whole {
part p;
map_t m;
};
lager::state<whole> state = lager::make_state(whole{});
lager::cursor<part> part_cursor =
state.zoom(lager::lenses::attr(&whole::p));
lager::cursor<map_t> map_cursor =
state.zoom(lager::lenses::attr(&whole::m));
lager::cursor<int> int_cursor =
map_cursor.zoom(lager::lenses::at("foo"))
.zoom(lager::lenses::or_default);
```
Will produce the following error in MSVC when attempting to zoom in on the map element:
```
.../immer/detail/hamts/node.hpp(300,26): error C2059: syntax error: ''symbol''
(followed by many more lines of error message)
```
Qualifying the explicit destructor call with `T::` satisfies the compiler.
=> Fix MSVC compile error C2059

immer/detail/rbts/rrbtree.hpp
In MSVC a constexpr variable loses its constexpr-ness when being captured by a lambda, so the use of `size` in `aligned_storage_t` results in:
`error C2975: '_Len': invalid template argument for 'std::aligned_storage_t', expected compile-time constant expression`
=> Fix msvc c2975

immer/detail/hamts/node.hpp
This fixes the MSVC madness I was experiencing before. This compiles in both C++17 and C++20 mode.
=> Use destroy_at to call explicit destructor in make_inner_n

immer/detail/hamts/champ_iterator.hpp, immer/detail/iterator_facade.hpp, test/array_transient/default.cpp, test/flex_vector/generic.ipp, test/flex_vector_transient/generic.ipp, test/map/generic.ipp, test/map_transient/generic.ipp, test/set/generic.ipp, test/set_transient/generic.ipp, test/table/generic.ipp, test/table_transient/generic.ipp, test/util.hpp, test/vector/generic.ipp, test/vector_transient/generic.ipp
Addresses #240, as well as finding a problem with `iterator_facade` not being able to model `random_access_iterator`.
Define tests on each container that it satisfies the intended range concept. (This will transitively validate the iterators as well)
- Fix: `champ_iterator()` was not `default_initializable`, which is a required for `semiregular`, which is required for iterators.
- Fix: `iterator_facade::operator[]` returned a `reference_proxy`, while `iterator_facade::operator*` returns a `ReferenceT`. The `random_access_iterator` concept requires that the operators return an identical type.
=> Fixes and tests for C++20 Range compatibility

doc/CMakeLists.txt
This makes things rely less on their current relative locations in the sources.
=> cmake: use ${CMAKE_CURRENT_SOURCE_DIR} where possible

immer/config.hpp
The current implementation of IMMER_THROW when exceptions are disabled relies on the compiler converting a character array to a truthy value, which can throw warnings and is not truly portable. Instead, we can use the comma operator to portably add additional data to an assertion: https://en.cppreference.com/w/cpp/error/assert.
=> Fix portability of IMMER_THROW when exceptions are disabled

immer/box.hpp, test/box/generic.ipp
Thanks @alex-sparus for reporting and fixing this one!
Based on: https://github.com/alex-sparus/immer/commit/c29e7ff9ac8478e78ba568d3d74a7a7c937456f9
=> Make immer::box work with forward declared types

immer/detail/util.hpp, immer/heap/debug_size_heap.hpp
This PR effectively adds a simple implementation of `std::aligned_storage` in the `immer::detail` namespace to avoid using the `std` one which causes deprecation warnings. This is meant to close #283.
=> Remove usage of `std::aligned_storage` to switch off deprecation warnings in C++23

CMakeLists.txt, immer/config.hpp
same as https://github.com/arximboldi/lager/pull/205
=> Allow users to explicitly enable or disable exceptions

immer/detail/hamts/bits.hpp, immer/detail/hamts/champ.hpp, immer/detail/hamts/champ_iterator.hpp, immer/detail/hamts/node.hpp, immer/extra/persist/detail/champ/output.hpp, immer/extra/persist/detail/rbts/pool.hpp, immer/extra/persist/xxhash/xxhash.hpp, immer/extra/persist/xxhash/xxhash_64.cpp, immer/table.hpp, test/extra/persist/CMakeLists.txt, test/extra/persist/test_hash_size.cpp
TODO:
- Make a test with WASM and try to read a map from JSON
=> Support hash size that's not std::size_t
