- immer/box.hpp
- test/box/vector-of-boxes-transient.cpp
> Fix problem when using transients in combination with vector of boxes

- immer/detail/rbts/rbtree.hpp
- immer/detail/rbts/rrbtree.hpp
- immer/flex_vector.hpp
- immer/vector.hpp
- test/vector/issue-46.cpp
> Fix embarrasing bug in vector<> operator==

- immer/array.hpp
- immer/detail/arrays/no_capacity.hpp
- immer/detail/arrays/with_capacity.hpp
- immer/detail/hamts/champ.hpp
- immer/detail/rbts/rbtree.hpp
- immer/detail/rbts/rrbtree.hpp
- immer/flex_vector.hpp
- immer/flex_vector_transient.hpp
- immer/map.hpp
- immer/set.hpp
- immer/vector.hpp
- immer/vector_transient.hpp
- test/flex_vector/issue-47.cpp
> Fix global initialization order fiasco

- immer/detail/hamts/champ_iterator.hpp
- immer/detail/rbts/rbtree_iterator.hpp
- immer/detail/rbts/rrbtree_iterator.hpp
- test/map/issue-56.cpp
Supercedes: https://github.com/arximboldi/immer/pull/56
> Fix -> operator in iterators

- immer/detail/hamts/bits.hpp
- immer/detail/hamts/champ.hpp
- immer/detail/hamts/champ_iterator.hpp
- immer/detail/hamts/node.hpp
- immer/map.hpp
- immer/set.hpp
- test/map/B6.cpp
- test/map/generic.ipp
- test/set/B6.cpp
I still have to refine the implementation, but the idea is clear.
I have some issues with building tests, will continue tomorrow.
Looking forward for the review :)
> Map B=6 support.

- .gitignore
- doc/index.rst
- doc/utilities.rst
- immer/atom.hpp
- immer/box.hpp
- immer/detail/hamts/champ.hpp
- immer/detail/hamts/champ_iterator.hpp
- immer/detail/hamts/node.hpp
- immer/refcount/no_refcount_policy.hpp
- immer/refcount/refcount_policy.hpp
- immer/refcount/unsafe_refcount_policy.hpp
- test/atom/default.cpp
- test/atom/gc.cpp
- test/atom/generic.ipp
- test/vector/issue-74.cpp
This branch also fixes some of the UB found in issue #74
> Add atom<> type in the spirit of Clojure atoms

- immer/heap/debug_size_heap.hpp
Would resolve issue https://github.com/arximboldi/immer/issues/74
> Fix UB on MacOS: use 16 (not 8) byte offset in debug_size_heap

- .gitignore
- BUILD
Based on: https://github.com/lhftio/immer
> Add minimal Bazel support

- .gitignore
- CMakeLists.txt
- benchmark/vector/drop.hpp
- benchmark/vector/take.hpp
- immer/array.hpp
- immer/array_transient.hpp
- immer/atom.hpp
- immer/box.hpp
- immer/config.hpp
- immer/flex_vector.hpp
- immer/flex_vector_transient.hpp
- immer/map.hpp
- immer/set.hpp
- immer/vector.hpp
- immer/vector_transient.hpp
> Add [[nodiscard]] whenever recommendable

- immer/set.hpp
please merge this simple typo fix :)
> fixed typo in comment of set.hpp

- extra/fuzzer/array.cpp
- extra/fuzzer/map-gc.cpp
- extra/fuzzer/map.cpp
- extra/fuzzer/set-gc.cpp
- extra/fuzzer/set.cpp
Some work in progress, just for the shake of sharing the code
> add fuzzers for array, map and set

- immer/detail/iterator_facade.hpp
Fix issues with iterator facade @audiofanatic found from merging #125
> Fix iterator facade not properly exposing iterator traits

- immer/set.hpp
- test/set/generic.ipp
Added find method to set, analogous to map. Fixes #121.
> Added set::find

- .dir-locals.el
- .travis.yml
- immer/detail/hamts/node.hpp
- test/map/generic.ipp
> Remove over-constraining assertion

- immer/memory_policy.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arximboldi/immer/140)
> Fix typo: chungs -> chunks.

- immer/detail/hamts/champ.hpp
- immer/detail/rbts/rbtree.hpp
- immer/detail/rbts/rrbtree.hpp
- immer/flex_vector.hpp
- immer/flex_vector_transient.hpp
- immer/vector.hpp
- immer/vector_transient.hpp
> Fix exit-time destructor warnings

- immer/flex_vector.hpp
- immer/flex_vector_transient.hpp
- immer/vector.hpp
- immer/vector_transient.hpp
- test/vector/issue-177.cpp
> Fix issue #177

- .github/workflows/test.yml
- CMakeLists.txt
- immer/box.hpp
- immer/detail/iterator_facade.hpp
- immer/detail/rbts/rrbtree.hpp
- immer/transience/gc_transience_policy.hpp
- nix/benchmarks.nix
- shell.nix
- test/box/generic.ipp
- test/flex_vector/generic.ipp
- test/map/generic.ipp
- test/set/generic.ipp
- test/vector/generic.ipp
- tools/include/catch.hpp
- tools/with-tee.bash
> Fix C++20 issues

- .github/workflows/test.yml
- .gitignore
This should fix the issues that @dwightguth is experiencing.
> Fix GitHub actions

- default.nix
Fixes both issues mentioned in #100
> Nix build issues

- extra/fuzzer/map-gc.cpp
- extra/fuzzer/map-st.cpp
- extra/fuzzer/map.cpp
- extra/fuzzer/set-gc.cpp
- extra/fuzzer/set-st.cpp
- extra/fuzzer/set.cpp
- immer/algorithm.hpp
- immer/detail/hamts/champ.hpp
- test/map/generic.ipp
- test/set/generic.ipp
FYI @mvtec-richter I've changed a bit the API, fixed some small issues, added it to the fuzzing infrastructure (so it gets tested at https://oss-fuzz.com/) and documented it.
> Polish the new diffing algorithm

- immer/detail/arrays/with_capacity.hpp
- immer/detail/hamts/champ.hpp
- immer/map.hpp
- immer/map_transient.hpp
- test/map/generic.ipp
- test/map_transient/generic.ipp
- test/vector/generic.ipp
This adds a transient version for `map::update()`. It also fixes a couple of bugs found along the way.
> Transient `map::update()`

- benchmark/set/erase.hpp
- benchmark/set/erase.ipp
- benchmark/set/string-box/erase.cpp
- benchmark/set/string-long/erase.cpp
- benchmark/set/string-short/erase.cpp
- benchmark/set/unsigned/erase.cpp
- immer/detail/hamts/champ.hpp
- immer/detail/hamts/node.hpp
- immer/map.hpp
- immer/map_transient.hpp
- immer/set.hpp
- immer/set_transient.hpp
- test/set_transient/generic.ipp
Also some other small bug-fixes and improvements.
> Transients for HAMT deletion operations

- doc/transients.rst
- immer/detail/hamts/champ.hpp
- immer/map.hpp
- immer/map_transient.hpp
- immer/set.hpp
- immer/set_transient.hpp
- immer/table.hpp
- immer/table_transient.hpp
> Table fixes and transient tweaks

- immer/detail/hamts/champ.hpp
- immer/detail/hamts/node.hpp
- immer/detail/rbts/node.hpp
- immer/detail/rbts/operations.hpp
- immer/detail/rbts/rbtree.hpp
- immer/detail/type_traits.hpp
- immer/map.hpp
- immer/table.hpp
- test/map/generic.ipp
> HAMT transients: move mutable inner nodes when posible during removal

- extra/fuzzer/map-st-str-conflict.cpp
- extra/fuzzer/set-st-str-conflict.cpp
> Add fuzzers that produce more conflicts for HAMTs

- immer/array.hpp
- immer/flex_vector.hpp
- immer/map.hpp
- immer/set.hpp
- immer/vector.hpp
- test/map/generic.ipp
- test/set/generic.ipp
- test/vector/generic.ipp
I decided not to change the API of `update_if_exists` to return a `bool`. This could however maybe help.
> Add identity API

- .github/workflows/test.yml
- CMakeLists.txt
New release includes:
- New `table` data-structure
- Transients for `map`, `set` and `map`
- New `update_if_exists` method for `map` and `set`
- Various bug-fixes and performance improvements
> Prepare release 0.8.0

- .github/workflows/test.yml
- test/oss-fuzz/flex-vector-0.cpp
- test/oss-fuzz/flex-vector-bo-0.cpp
- test/oss-fuzz/flex-vector-gc-0.cpp
- test/oss-fuzz/map-st-2.cpp
- test/oss-fuzz/map-st-str-0.cpp
- test/oss-fuzz/set-gc-1.cpp
https://issues.guix.gnu.org/issue/63330
> Fix includes

- immer/detail/hamts/champ.hpp
- immer/detail/hamts/node.hpp
- immer/map.hpp
- immer/set.hpp
Based entirely on @maierlars work , done in #244.
> set/map nothrow move constructible/assignable

- immer/config.hpp
Related: https://github.com/arximboldi/lager/issues/204
> Fix exception detection code
